### ISSUE TITLE
Support Coverity

### ISSUE THREAD

**Issue by ken-matsui** [poacpm/poac#118]

**Comment by matken11235** [comment]
Build failed owing to SIP enabled problem on macOS.
To specify `osx_image: xcode 6.4` according to the following link however, it will not compile with C++17.
https://docs.travis-ci.com/user/coverity-scan/#macos-support

In addition, I tried to use Linux(https://github.com/poacpm/poac/commit/8a4ec9eb622cdf06429147c8e87e00d3e67fb79a), but at present (June 2019), I could not build because only xenial was supported, and so g++(5.2) and boost(1.58.0) is old.

Therefore, the countermeasure is shown below:
* Wait until the problem on macOS is solved.
* Wait for travis-ci to support to the new distribution.
* Repository becomes dirty by the increase of the file, nevertheless build referring to https://github.com/acidanthera/Lilu/commit/b35c5bf200f57b3bcf3e2e84622bd630ba2a27e8.

**Comment by ken-matsui** [comment]
[.github/workflows/coverity.yml](https://github.com/poacpm/poac/blob/master/.github/workflows/coverity.yml)
